CREATE SCHEMA IF NOT EXISTS Actividad8 DEFAULT CHARACTER SET utf8 ;
use Actividad8;

CREATE TABLE IF NOT EXISTS Pregunta (
  IdPregunta INT NOT NULL AUTO_INCREMENT,
  PreguntaXML VARCHAR(700) NOT NULL,
  PRIMARY KEY (IdPregunta))
ENGINE = InnoDB;

